### ISSUE TITLE
Опции слайдера + баги

### ISSUE THREAD

**Issue by Nelliza** [DenisKhodasevich/Slider#1]
Сейчас у тебя в слайдере вместо размера шага используется количество шагов, это не совсем очевидно, к тому же, если значение для количества шагов поставить больше величины интервала, появляются баги:
![1](https://user-images.githubusercontent.com/19621113/75653987-b241bf80-5c6f-11ea-9b87-5fd41f7deb74.gif)

**Comment by Nelliza** [comment]
Также трек (полоска) является не только элементом дизайна, но также имеет функционал: при клике по треку ползунок должен перемещаться в место клика

**Comment by Nelliza** [comment]
Еще баги:

При установке размера шага больше максимального значения ползунок выходит за пределы контейнера
![1](https://user-images.githubusercontent.com/19621113/76792362-f5557400-67d3-11ea-8cb7-a7308d0ba28a.gif)

**Comment by Nelliza** [comment]
Есть возможность установить равные `min` и `max` значения, при этом значения ползунков становятся некорректными
![2](https://user-images.githubusercontent.com/19621113/76792488-364d8880-67d4-11ea-84ee-acf3f0e44e06.gif)

**Comment by Nelliza** [comment]
> Есть возможность установить равные `min` и `max` значения, при этом значения ползунков становятся некорректными
> ![2](https://user-images.githubusercontent.com/19621113/76792488-364d8880-67d4-11ea-84ee-acf3f0e44e06.gif)


Баг не исправлен - так ведь тоже не может быть, согласись? )
![1](https://user-images.githubusercontent.com/19621113/77234389-0f6dc880-6bbf-11ea-93d9-ed5cb42b99f0.gif)

**Comment by Nelliza** [comment]
> Есть возможность установить равные `min` и `max` значения, при этом значения ползунков становятся некорректными
> ![2](https://user-images.githubusercontent.com/19621113/76792488-364d8880-67d4-11ea-84ee-acf3f0e44e06.gif)

Баг не исправлен - так ведь тоже не может быть, согласись? )
![1](https://user-images.githubusercontent.com/19621113/77234389-0f6dc880-6bbf-11ea-93d9-ed5cb42b99f0.gif)

**Comment by Nelliza** [comment]
Теперь поле со значением бегунка некорректно реагирует на изменение его положения:
![1](https://user-images.githubusercontent.com/19621113/79670190-e0507400-81c9-11ea-96fd-262b59592645.gif)

**Comment by Nelliza** [comment]
Есть возможность задать `min` значение больше `max`, и также значение левого ползунка больше правого
![1](https://user-images.githubusercontent.com/19621113/88666890-5463b780-d0e9-11ea-8884-e53cd65e26c6.gif)

**Comment by Nelliza** [comment]
Метки слетели (
![1](https://user-images.githubusercontent.com/19621113/90281413-329e5a80-de75-11ea-96c4-56ffb341ef1d.png)

**Comment by DenisKhodasevich** [comment]
Странно, у меня во всех браузерах нормально отображается. Я думал, что, может быть, не все изменения на ГХ залились, попробовал заново скачать проект и установить - но нет, все нормально работает. Возможно, у тебя не все изменения подтянулись, попробуй заново проект скачать и установить или кэш браузера почистить.

**Comment by Nelliza** [comment]
При клике на отметку шкалы устанавливается неточное значение, не соответствующее цифровой отметке:
![1](https://user-images.githubusercontent.com/19621113/93133350-bb601e80-f6df-11ea-83e3-011982b734a1.gif)
Такое поведение, как сейчас, ожидаемо при клике на трекер (полоску), тогда как клик на цифровую отметку шкалы предназначен для установки ползунку идентичного отметке значения

**Comment by Nelliza** [comment]
https://github.com/DenisKhodasevich/Slider/commit/2f1c5106f9dc665c0b6f13a8ac8faeed5b691a49#r42463727

**Comment by DenisKhodasevich** [comment]
Эту часть кода я уже исправил в последнем [коммите](https://github.com/DenisKhodasevich/Slider/commit/325b0f000c8fddede29fca430b785e486e8b487f). Только я в нем не ссылался на этот ишью.
