### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by Nelliza** [DenisKhodasevich/Slider#11]
https://github.com/DenisKhodasevich/Slider/blob/325b0f000c8fddede29fca430b785e486e8b487f/src/plugin/View/MainView.ts#L17-L37
Приведи плиз синтаксис к единому виду, и поправь пожалуйста везде в проекте

**Comment by Nelliza** [comment]
https://github.com/DenisKhodasevich/Slider/blob/325b0f000c8fddede29fca430b785e486e8b487f/src/plugin/Model/Model.ts#L12-L27
Убери пожалуйста пустые строки между объявлениями приватных свойств классов

**Comment by Nelliza** [comment]
https://github.com/DenisKhodasevich/Slider/blob/1af62ee1bb1e6c62b5da9d511b458cca5267672e/.eslintrc#L12
Не стоит отключать правило, можно использовать параметр `exceptAfterSingleLine` для пропуска однострочных полей https://eslint.org/docs/rules/lines-between-class-members

**Comment by Nelliza** [comment]
https://github.com/DenisKhodasevich/Slider/blob/master/src/plugin/View/MainView.ts#L88
А для чего здесь `setTimeout()`?

**Comment by Nelliza** [comment]
https://github.com/DenisKhodasevich/Slider/blob/d238fa9832dc1e6758cf791724d75c6186cfcb95/src/plugin/View/MainView.ts#L88-L90
А для чего здесь `setTimeout()`?

**Comment by DenisKhodasevich** [comment]
> https://github.com/DenisKhodasevich/Slider/blob/d238fa9832dc1e6758cf791724d75c6186cfcb95/src/plugin/View/MainView.ts#L88-L90
> 
> 
> А для чего здесь `setTimeout()`?

Раньше обработчик клика был реализован по-другому, и нужно было, чтобы он срабатывал не сразу. Но сейчас вроде и без этого все нормально работает, поэтому уберу.

**Comment by Nelliza** [comment]
https://github.com/DenisKhodasevich/Slider/blob/c6464a6950408944cb88bbaa64f3c7955599a0a6/src/plugin/main/slider.pug#L3
В таких случаях, когда нет необходимости в использовании шаблонных строк, приводить к строке лучше явно

**Comment by Nelliza** [comment]
https://github.com/DenisKhodasevich/Slider/blob/c6464a6950408944cb88bbaa64f3c7955599a0a6/src/plugin/View/MainView.ts#L144-L146
Здесь лучше объединить присвоение в одну инструкцию

**Comment by Nelliza** [comment]
https://github.com/DenisKhodasevich/Slider/blob/c6464a6950408944cb88bbaa64f3c7955599a0a6/src/plugin/View/HandleView.ts#L67-L69
Не очень удачное именование обработчиков )

https://github.com/DenisKhodasevich/Slider/blob/c6464a6950408944cb88bbaa64f3c7955599a0a6/src/demo-page/DemoPage.ts#L67
https://github.com/DenisKhodasevich/Slider/blob/c6464a6950408944cb88bbaa64f3c7955599a0a6/src/demo-page/DemoPage.ts#L69
https://github.com/DenisKhodasevich/Slider/blob/c6464a6950408944cb88bbaa64f3c7955599a0a6/src/demo-page/DemoPage.ts#L78
https://github.com/DenisKhodasevich/Slider/blob/c6464a6950408944cb88bbaa64f3c7955599a0a6/src/demo-page/DemoPage.ts#L80
То же самое

**Comment by DenisKhodasevich** [comment]
> > https://github.com/DenisKhodasevich/Slider/blob/d238fa9832dc1e6758cf791724d75c6186cfcb95/src/plugin/View/MainView.ts#L88-L90
> > 
> > А для чего здесь `setTimeout()`?
> 
> Раньше обработчик клика был реализован по-другому, и нужно было, чтобы он срабатывал не сразу. Но сейчас вроде и без этого все нормально работает, поэтому уберу.

Я вспомнил, зачем я так делал. Например, если активированы оба ползунка, и я хочу установить их в одинаковое положение перетаскиванием, то в том случае, если я перетащу ползунок немного дальше, чем нужно, происходит срабатывание клика и другой ползунок перемещается. Поэтому вернул `setTimeout()` обратно, чтобы клик не срабатывал сразу после события mouseup.

![1](https://user-images.githubusercontent.com/43818614/94376939-27f30880-0137-11eb-82cb-4c7fc0c562ff.gif)

**Comment by Nelliza** [comment]
Похоже на костыль, честно говоря )

**Comment by Nelliza** [comment]
> Я вспомнил, зачем я так делал. Например, если активированы оба ползунка, и я хочу установить их в одинаковое положение перетаскиванием, то в том случае, если я перетащу ползунок немного дальше, чем нужно, происходит срабатывание клика и другой ползунок перемещается. Поэтому вернул `setTimeout()` обратно, чтобы клик не срабатывал сразу после события `mouseup`.

Как это - активированы оба ползунка? Пока не очень понятно и решение выглядит как костыль )

**Comment by DenisKhodasevich** [comment]
> > Я вспомнил, зачем я так делал. Например, если активированы оба ползунка, и я хочу установить их в одинаковое положение перетаскиванием, то в том случае, если я перетащу ползунок немного дальше, чем нужно, происходит срабатывание клика и другой ползунок перемещается. Поэтому вернул `setTimeout()` обратно, чтобы клик не срабатывал сразу после события `mouseup`.
> 
> Как это - активированы оба ползунка? Пока не очень понятно и решение выглядит как костыль )

Значит, что второй ползунок активирован (у меня он активируется дата-атрибутом `data-is-range`). Когда срабатывает событие `mouseup`, событие `click` тоже срабатывает, поэтому получается такой эффект, как в гифке, которую я приложил выше. Поэтому я отключаю событие `click` при срабатывании события `mousemove`, а в событии `mouseup` снова его включаю. Но без `setTimeout()` он будет включен сразу же, и тогда этот эффект останется.
