### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by Nelliza** [DenisKhodasevich/Slider#2]
У меня не запускаются тесты
![1](https://user-images.githubusercontent.com/19621113/76795599-ab23c100-67da-11ea-953a-614c431aba0a.png)

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/77234109-04b23400-6bbd-11ea-9107-c4d4cfe76405.png)
Отчет о покрытии не настроен

**Comment by Nelliza** [comment]
Презентер тоже нужно покрыть тестами

**Comment by DenisKhodasevich** [comment]
У меня там все методы приватные, в таком случае тоже нужно тестировать?

**Comment by Nelliza** [comment]
> У меня там все методы приватные, в таком случае тоже нужно тестировать?

Ну как минимум можно тестировать корректную инициализацию и подписку на события.

Но вообще это кажется странным, что все методы у презентера приватные, т.к. общение между демо-панелью и самим плагином ведь происходит с помощью публичных методов, которые обычно предоставляет как раз контроллер/презентер

**Comment by Nelliza** [comment]
Один из тестов не проходит:
![1](https://user-images.githubusercontent.com/19621113/90283731-5368af00-de79-11ea-9f6d-3f7554d5c6c9.png)

**Comment by Nelliza** [comment]
Один из тестов в презентере падает сейчас
